networks:
  backend:
    name: backend
    driver: bridge

services:
  messenger:
    image: bitnami/kafka
    hostname: messenger
    container_name: messenger
    networks:
      - backend
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://messenger:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  rest:
    build: ./rest
    container_name: rest
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - messenger

  calculator-service:
    build: ./calculator-service
    container_name: calculator-service
    networks:
      - backend
    depends_on:
      - messenger
